added custom fonts
The-Major-Project/Design-and-Develop-frontend pull request #7
Opened 2021-09-07 17:46 UTC by mihirverma7781

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Light.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Light.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-UltraLight.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-UltraLight.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-ExtraBold.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-ExtraBold.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Heavy.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Heavy.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Regular.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Regular.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Thin.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Thin.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-SemiBold.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-SemiBold.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Black.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Black.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Bold.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Bold.ttf";
```

2021-09-07 18:38 UTC, mihirverma7781 commented on src/index.js
> +import './fonts/gilroy/Gilroy-Medium.ttf';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/The-Major-Project/Design-and-Develop-frontend/pullRequest?prid=8041234)
```suggestion
import "./fonts/gilroy/Gilroy-Medium.ttf";
```

2021-09-08 10:16 UTC, yash-sharma01 commented on src/index.css
> +  font-family: "gthin";
It should be ultraLight

2021-09-08 10:18 UTC, yash-sharma01 requested changes
Change the name of last ultraLight font

2021-09-08 10:19 UTC, yash-sharma01 approved these changes

2021-09-08 10:19 UTC, merged