Mj dashboard ppost card
The-Major-Project/Design-and-Develop-frontend pull request #82
Opened 2021-09-29 13:26 UTC by manvijain08

2021-09-29 15:10 UTC, yash-sharma01 commented on src/components/DashboardPostCard/index.js
> +          hasShadow
I think removing the hasShadow will look better!

2021-09-29 19:30 UTC, mihirverma7781 requested changes

2021-09-29 19:30 UTC, mihirverma7781 commented on src/components/DashboardPostCard/index.js
> +            <div className="text-gray-500 texr-sm">15 jun 2021</div>
make the "texr-sm" to "text-sm"

2021-09-30 11:48 UTC, mihirverma7781 approved these changes

2021-09-30 11:53 UTC, mihirverma7781 approved these changes

2021-09-30 11:54 UTC, mihirverma7781 approved these changes

2021-09-30 11:55 UTC, yash-sharma01 approved these changes

2021-09-30 11:55 UTC, merged